apiVersion: v2
appVersion: 2.0.21
description: A Helm chart for the cambricon device-plugin on Kubernetes
home: https://github.com/Cambricon/cambricon-k8s-device-plugin/
kubeVersion: '>= 1.14.0'
name: device-plugin
type: application
version: 2.0.21
